//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatesObject {
    
        public decimal vendorId { get; set; }
        public long countryId { get; set; }

        public string countryName { get; set; }
        public decimal service_typeId { get; set; }

        public string serviceTypeDescription { get; set; }
        public decimal measure_unitId { get; set; }
        public string measureUnitDescription { get; set; }
        public string state { get; set; }
        public decimal price { get; set; }
        public string status { get; set; }
    
    }
}
