//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_view
    {
        public decimal customerid { get; set; }
        public string logo { get; set; }
        public string company_name { get; set; }
        public long countryId { get; set; }
        public string CountryName { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string zipcode { get; set; }
        public string customer_status { get; set; }
        public string full_name { get; set; }
        public Nullable<decimal> membershipId { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> final_date { get; set; }
        public Nullable<System.DateTime> initial_date { get; set; }
        public Nullable<decimal> number_shipments { get; set; }
        public Nullable<decimal> max_number_shipments { get; set; }
    }
}
