//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership_history
    {
        public decimal membershipId { get; set; }
        public decimal customerId { get; set; }
        public string card_number { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public System.DateTime payment_date { get; set; }
        public System.DateTime initial_date { get; set; }
        public System.DateTime final_date { get; set; }
        public decimal membership_HistoryId { get; set; }
        public decimal number_shipments { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual Memberships_levels Memberships_levels { get; set; }
    }
}
