//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rates
    {
        public decimal vendorId { get; set; }
        public long countryId { get; set; }
        public decimal service_typeId { get; set; }
        public decimal measure_unitId { get; set; }
        public string state { get; set; }
        public decimal price { get; set; }
        public string status { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual measure_units measure_units { get; set; }
        public virtual vendors vendors { get; set; }
    }
}
