//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurring_addresses
    {
        public decimal addressId { get; set; }
        public decimal customerId { get; set; }
        public Nullable<long> countryId { get; set; }
        public string consignee_name { get; set; }
        public string target_company { get; set; }
        public string phone_number { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string zipcode { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual customers customers { get; set; }
    }
}
