//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shipments()
        {
            this.shipment_attachment = new HashSet<shipment_attachment>();
            this.shipment_cost = new HashSet<shipment_cost>();
            this.shipment_notes = new HashSet<shipment_notes>();
            this.shipment_services = new HashSet<shipment_services>();
            this.shipment_tracking = new HashSet<shipment_tracking>();
        }
    
        public decimal shipmentId { get; set; }
        public decimal customerId { get; set; }
        public decimal userId { get; set; }
        public long countryId { get; set; }
        public decimal service_typeId { get; set; }
        public string consignee_name { get; set; }
        public string target_company { get; set; }
        public string phone_number { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string zipcode { get; set; }
        public string shipping_terms { get; set; }
        public string tnc_accepted { get; set; }
        public System.DateTime shipment_date { get; set; }
        public string preferred_vendor { get; set; }
        public Nullable<System.DateTime> estimated_delivery_date { get; set; }
        public string description { get; set; }
        public string current_tracking { get; set; }
        public Nullable<System.DateTime> current_tracking_date { get; set; }
        public string status { get; set; }
        public Nullable<decimal> vendorId { get; set; }
        public string purcharse_order { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual customers customers { get; set; }
        public virtual service_types service_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment_attachment> shipment_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment_cost> shipment_cost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment_notes> shipment_notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment_services> shipment_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment_tracking> shipment_tracking { get; set; }
        public virtual users users { get; set; }
        public virtual vendors vendors { get; set; }
    }
}
