//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment_services
    {
        public decimal shipmentId { get; set; }
        public decimal service_typeId { get; set; }
        public decimal measure_unitId { get; set; }
        public decimal quantity { get; set; }
        public decimal estimated_unit_price { get; set; }
        public Nullable<decimal> confirmed_unit_price { get; set; }
    
        public virtual measure_units measure_units { get; set; }
        public virtual shipments shipments { get; set; }
    }
}
