//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransShipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment_attachment
    {
        public decimal shipmentId { get; set; }
        public decimal file_typeId { get; set; }
        public decimal shipment_attachmentId { get; set; }
        public decimal userId { get; set; }
        public string description { get; set; }
        public System.DateTime creation_date { get; set; }
        public string file_name { get; set; }
    
        public virtual file_types file_types { get; set; }
        public virtual shipments shipments { get; set; }
        public virtual users users { get; set; }
    }
}
